core/urls.py
from django.conf.urls import url
from views import index, create_user, edit_user, delete_user, courses

urlpatterns = (
    url(r'^$', index, name='index'),
    url(r'^user/create/$', create_user, name='create_user'),
    url(r'^user/edit/(?P<pk>\d+)/$', edit_user, name='edit_user'),
    url(r'^user/delete/(?P<pk>\d+)/$', delete_user, name='delete_user'),
    url(r'^courses/$', courses, name='courses'),
)

synergy_way_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
]

core/models.py
from django.db import models
from db.connect_to_db import ConnectDB

STATUS = (('inactive', 'Inactive'),
          ('active', 'Active'))


class User(models.Model):
    @classmethod
    def add_user(cls, **kwargs):
        procedure_name = 'add_user'
        values = (kwargs.get('name'), kwargs.get('email'), kwargs.get('phone'),
                  kwargs.get('mobile_phone'), kwargs.get('status'))
        ConnectDB().execute_procedure(procedure_name, values)

    @classmethod
    def get_all_users(cls):
        list_users = ConnectDB().select('SELECT * FROM get_all_users()')
        return list_users

    @classmethod
    def get_user(cls, user_id):
        user = ConnectDB().select_user('SELECT * FROM get_user(' + user_id + ')')
        return user

    @classmethod
    def edit_user(cls, user_id, **kwargs):
        procedure_name = 'edit_user'
        values = (user_id, kwargs.get('name'), kwargs.get('email'), kwargs.get('phone'),
                  kwargs.get('mobile_phone'), kwargs.get('status'))
        ConnectDB().execute_procedure(procedure_name, values)

    @classmethod
    def filter_by_name(cls, name):
        users = ConnectDB().select("SELECT * FROM get_user_by_name('" + name + "')")
        print users
        return users

    @classmethod
    def delete_user(cls, user_id):
        procedure_name = 'delete_user'
        ConnectDB().execute_procedure(procedure_name, user_id)

    @classmethod
    def get_courses_for_user(cls, user_id):
        sql = 'SELECT * FROM get_user_courses(' + user_id + ')'
        list_courses = ConnectDB().select(sql)
        return list_courses

    @classmethod
    def update_user_courses(cls, user_id, course_codes):
        old_courses = cls.get_courses_for_user(user_id)
        for old_course in old_courses:
            if old_course[0] not in course_codes:
                procedure_name = 'delete_course_for_user'
                ConnectDB().execute_procedure(procedure_name, (user_id, old_course[0]))
            else:
                course_codes.remove(old_course[0])
        procedure_name = 'add_user_courses'
        for course_code in course_codes:
            print course_code
            values = (user_id, course_code)
            ConnectDB().execute_procedure(procedure_name, values)

    @classmethod
    def get_all_courses(cls):
        list_courses = ConnectDB().select('SELECT * FROM get_all_courses()')
        return list_courses

core/forms.py
from django import forms
from models import STATUS
import re
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Button
from models import User


class UserForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField(required=False, help_text='Format +xx(xxx)xxxxxxx')
    mobile_phone = forms.CharField(required=False, help_text='Format +xx(xxx)xxxxxxx')
    status = forms.ChoiceField(choices=STATUS, required=False)
    button_name = 'Create'

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', self.button_name))

    def clean_name(self):
        if self.has_digit(self.cleaned_data['name']):
            raise forms.ValidationError('Name cannot contain any digit!')
        return self.cleaned_data['name']

    @staticmethod
    def has_digit(name):
        return bool(re.search(r'\d', name))


class EditUserForm(UserForm):
    name = forms.CharField(disabled=True)
    courses = User.get_all_courses()
    course = forms.ChoiceField(choices=courses, required=False)
    button_name = 'Save'

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Button('add', '+', css_class='button-add-course'))

core/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from .models import User
from .forms import UserForm, EditUserForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    filter_name = request.GET.get('filter_by_name')
    if filter_name:
        users_all = User.filter_by_name(str(filter_name))
    else:
        filter_name = ''
        users_all = User.get_all_users()
    items_number = [10, 15, 20]
    number = request.GET.get('number', items_number[0])
    paginator = Paginator(users_all, number)
    page = request.GET.get('page')
    try:
        users_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        users_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range, deliver last page of results.
        users_page = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'users': users_page, 'number': number, 'items_number': items_number,
                                          'filter_name': filter_name})


def create_user(request):
    form = UserForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            User.add_user(**form.cleaned_data)
            return render(request, 'create_user.html', {'form': form, 'message': 'User created successfully'})
    return render(request, 'create_user.html', {'form': form})


def edit_user(request, pk):
    user = User.get_user(pk)
    form = EditUserForm(request.POST or None, initial=user)
    user_courses = User.get_courses_for_user(pk)
    print user_courses
    if request.method == 'POST':
        if form.is_valid():
            User.edit_user(pk, **form.cleaned_data)
            User.update_user_courses(pk, request.POST.getlist('selected_courses'))
            user_courses = User.get_courses_for_user(pk)
            return render(request, 'edit_user.html',
                          {'form': form, 'message': 'Changes saved successfully', 'user_courses': user_courses})
    return render(request, 'edit_user.html', {'form': form, 'user_courses': user_courses})


def delete_user(request, pk):
    User.delete_user(pk)
    return redirect(reverse_lazy('index'))


def courses(request):
    return render(request, 'courses.html', {'courses': User.get_all_courses()})

templates/courses.html
{% extends 'index.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-12"><h4>COURSES</h4></div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table">
                <tr class="dark">
                    <th class="first-column">Name</th>
                    <th>Code</th>
                </tr>
                {% for course in courses %}
                    <tr class="white">
                        <td class="first-column">{{ course.1 }}</td>
                        <td>{{ course.0 }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/create_user.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if message %}
        <div class="alert alert-success" id="message" role="alert"><p>{{ message }}</p></div>
    {% endif %}

    <div class="row">
        <div class="col-sm-1">
            <a class="pull-left" href="{% url 'index' %}"><span class="glyphicon glyphicon-menu-left"></span> </a>
        </div>
        <div class="col-sm-8 col-sm-offset-2">
            <div class="create-user-form ">
                {% block title %}
                    <h4 class="text-center">CREATE USER</h4>
                {% endblock %}
                {% crispy form %}
            </div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    {% if message %}
        <script>
            $('document').ready(function () {
                setTimeout(function () {
                    window.location = '{% url 'index' %}'
                }, 3000)
            })
        </script>
    {% endif %}
{% endblock %}

templates/edit_user.html
{% extends 'create_user.html' %}
{% load static %}

{% block title %}
    <h4 class="text-center">CHANGE USER</h4>
{% endblock %}
{% block content %}
    {% if message %}
        <div class="alert alert-success" id="message" role="alert"><p>{{ message }}</p></div>
    {% endif %}
    {{ block.super }}
    <div class="selected-courses">

    </div>
{% endblock %}
{% block custom_js %}
    {% if message %}
        <script>
            $('document').ready(function () {
                setTimeout(function () {
                    window.location = '{% url 'index' %}'
                }, 3000)
            })
        </script>
    {% endif %}
    {% if user_courses %}
        <script>
            $('document').ready(function () {
                {% for user_course in user_courses %}
                    $('#id_course  option[value="{{ user_course.0}}"]').remove();
                    $('#div_id_course').append("<p id='{{ user_course.0 }}' class='custom-course'><input type='hidden'  name='selected_courses' " +
                            "value='{{ user_course.0 }}'>{{ user_course.1 }}<a href='#' class='remove_course'>" +
                            "<span class='glyphicon glyphicon-remove-circle'></span></a></p>");
                {% endfor %}
                if ($(":input[name='selected_courses']").length == 5) {
                    $('#button-id-add').css('display', 'none');
                }
            })
        </script>
    {% endif %}
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
    <link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static  "css/custom_style.css" %}"/>
    <link href="https://fonts.googleapis.com/css?family=Yesteryear" rel="stylesheet">
</head>
<body>

<div class="header-main">
    <div class="container">
        <h4 class="logo-text">Test for You</h4>

        <div class="header-links">

            <a class="{% if request.resolver_match.url_name != "courses" %}active{% endif %}"
               href="{% url 'index' %}">Users</a>
            <a class="{% if request.resolver_match.url_name == "courses" %}active{% endif %}"
               href="{% url 'courses' %}">Courses</a>

        </div>
    </div>
</div>
<div class="container">
    {% block content %}
        <div class="row">
            <div class="col-sm-1">
                <a href="{% url 'create_user' %}"><span class="glyphicon glyphicon-plus"></span> </a>
            </div>
            <div class="col-sm-3">
                <form class="form-inline" method="get" action=".">
                    <button type="submit" class="glyphicon glyphicon-search"></button>
                    <input type="text" class="filter_by_name" name="filter_by_name" value="{{ filter_name }}">

                </form>
            </div>
            <div class="col-sm-6">
                <h4 class="text-center">USERS</h4>
            </div>
            <div class="col-sm-2">
                <div class="btn-group">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-pagination"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        {{ number }}
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        {% for number in items_number %}
                            <li>
                                <a href="?number={{ number }}">{{ number }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table">
                    <tr class="dark">
                        <th class="first-column">Name</th>
                        <th>E-mail</th>
                        <th>Status</th>
                        <th class="last-column">Action</th>
                    </tr>
                    {% for user in users %}

                        <tr class="white">
                            <td class="first-column">{{ user.1 }}</td>
                            <td>{{ user.2 }}</td>
                            <td class="status_{{ user.3 }}">{{ user.3 }}</td>
                            <td class="last-column">
                                <a href="{% url 'edit_user' user.0 %}"><span class="glyphicon glyphicon-pencil"></span>
                                </a>
                                <a href="{% url 'delete_user' user.0 %}"><span
                                        class="glyphicon glyphicon-trash"></span> </a>
                            </td>
                        </tr>

                    {% endfor %}
                </table>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-12">
                <nav class="pagination-custom" aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% for page in users.paginator.page_range %}

                            <li><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}

                        <li>
                            <a href="?page={{ page }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    {% endblock %}
</div>

</body>
<script src="{% static  "js/jquery-1.12.3.min.js" %}"></script>
<script src="{% static  "js/bootstrap/bootstrap.min.js" %}"></script>
<script src="{% static  "js/custom.js" %}"></script>
{% block custom_js %}
{% endblock %}
</html>